import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import ClientLayout from '@/components/layouts/ClientLayout';

export const metadata = {
  title: "Brava Mama",
  description: "Generated by create next app",
};


export default function Layout({ children }) {
  return (
    <>
      <ClientLayout children={children} />
    </>
  );
}