import Footer from "./components/Layouts/Footer";
import Header from "./components/Layouts/Header";
import Sidebar from "./components/Layouts/Sidebar";

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      <div className="flex justify-between">
        <div className="w-1/6">
          <Sidebar />
        </div>
        <div className="w-5/6 bg-gray-400 h-screen p-4">
          {children}
        </div>
      </div>
      <Footer />
    </>
  );
}