import { NextUIProvider } from "@nextui-org/react";
import "../styles/main.scss";

export const metadata = {
  title: "Brava Mama",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
